name: Build macOS

on: workflow_dispatch

jobs:
  build-MacOS:
    name: Build StandaloneOSX (Mono)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: DragonBoy/Library
          key: Library-StandaloneOSX-Mono
          restore-keys: Library-

      - name: Set scripting backend
        run: |
          chmod +x set_scripting_backend_mac.sh
          ./set_scripting_backend_mac.sh "DragonBoy/ProjectSettings/ProjectSettings.asset" "StandaloneOSX" "Mono"

      - name: Build
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneOSX
          projectPath: DragonBoy
          buildName: DragonBoy
          allowDirtyBuild: true

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: DragonBoy-macOS
          path: build/StandaloneOSX
          if-no-files-found: error
